# https://pre-commit.com/
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      # tidy up extra whitespace at end of files
      - id: trailing-whitespace
      # ensure consistent newline endings for files (\n only)
      - id: end-of-file-fixer
      # fix newlines in general to prevent pesky windows users writing CRLF
      - id: mixed-line-ending
        args: [--fix=lf]
      # do not allow pdb/breakpoint statements to be checked in
      - id: debug-statements
  # code formatting
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [ --max-line-length=120 ]
  - repo: https://github.com/python/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--safe, --line-length=120]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        exclude: migrations
        args: ["--profile", "black", "--filter-files"]
